defaults:
  - override hydra/job_logging: custom
  - _self_

dirs:
  data: data
  raw: raw
  processed: processed
  final: final
  models: models

# Data loading
dataloader_num_workers: 4
batch_size: 8
gradient_accumulation_steps: 1
seed: 4242

# Model training
pretrained_model_id: intfloat/multilingual-e5-large
num_epochs: 3
num_warmup_steps: 50
learning_rate: 3e-4
first_momentum: 0.9
second_momentum: 0.999
weight_decay: 0.01
