defaults:
  - override hydra/job_logging: custom
  - _self_

dirs:
  data: data
  raw: raw
  processed: processed
  final: final
  models: models

# Data loading
dataloader_num_workers: 4
batch_size: 16
gradient_accumulation_steps: 8
seed: 4242

# Model training
pretrained_model_id: intfloat/multilingual-e5-base
num_epochs: 50
num_warmup_steps: 1000
logging_steps: 10
eval_steps: 250
learning_rate: 1e-5
first_momentum: 0.9
second_momentum: 0.999
weight_decay: 0.01

# Tracking
wandb: false
wandb_project: ScandiDPR
wandb_group: default
wandb_name: null
